services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: noddde
      POSTGRES_PASSWORD: noddde
      POSTGRES_DB: hotel_booking
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
