/**
 * Synthetic-fixture generator for the type-system stress test.
 *
 * Emits a self-contained TypeScript module that declares N aggregates
 * (each with M commands / M events), P projections, and S sagas, then
 * composes them all through `defineDomain`. The output is fed to
 * `tsc --extendedDiagnostics` by `run-type-perf.ts` to measure how the
 * compiler scales with the public type surface of `@noddde/core`.
 *
 * The shape of generated code intentionally mirrors what a realistic
 * domain author would write (matches the `samples/*` patterns) so the
 * perf numbers reflect production-like load rather than an artificial
 * minimum case.
 */

export interface StressFixtureOptions {
  /** Number of aggregates to generate. Must be >= 1. */
  aggregates: number;
  /** Commands per aggregate (1:1 with events). Defaults to 3. */
  commandsPerAggregate?: number;
  /** Number of projections. Defaults to ceil(aggregates / 3). */
  projections?: number;
  /** Number of sagas. Defaults to ceil(aggregates / 5). */
  sagas?: number;
  /** Import specifier for the core package. Defaults to "@noddde/core". */
  coreImport?: string;
}

export interface ResolvedStressFixtureOptions {
  aggregates: number;
  commandsPerAggregate: number;
  projections: number;
  sagas: number;
  coreImport: string;
}

export function resolveOptions(
  opts: StressFixtureOptions,
): ResolvedStressFixtureOptions {
  const aggregates = Math.max(1, opts.aggregates);
  return {
    aggregates,
    commandsPerAggregate: Math.max(1, opts.commandsPerAggregate ?? 3),
    projections: Math.max(0, opts.projections ?? Math.ceil(aggregates / 3)),
    sagas: Math.max(0, opts.sagas ?? Math.ceil(aggregates / 5)),
    coreImport: opts.coreImport ?? "@noddde/core",
  };
}

export function generateStressFixture(opts: StressFixtureOptions): string {
  const r = resolveOptions(opts);
  const lines: string[] = [];

  lines.push(
    `// AUTO-GENERATED stress fixture: ${r.aggregates} aggregates x ${r.commandsPerAggregate} commands, ${r.projections} projections, ${r.sagas} sagas`,
  );
  lines.push(
    `// Generated by packages/core/scripts/generate-stress-fixture.ts — do not edit by hand.`,
  );
  lines.push(`/* eslint-disable */`);
  lines.push(``);
  lines.push(`import {`);
  lines.push(`  defineAggregate,`);
  lines.push(`  defineDomain,`);
  lines.push(`  defineProjection,`);
  if (r.sagas > 0) lines.push(`  defineSaga,`);
  lines.push(`} from "${r.coreImport}";`);
  lines.push(`import type {`);
  lines.push(`  AggregateTypes,`);
  lines.push(`  DefineCommands,`);
  lines.push(`  DefineEvents,`);
  lines.push(`  DefineQueries,`);
  lines.push(`  Infrastructure,`);
  lines.push(`  ProjectionTypes,`);
  if (r.sagas > 0) lines.push(`  SagaTypes,`);
  lines.push(`} from "${r.coreImport}";`);
  lines.push(``);
  lines.push(`interface StressInfra extends Infrastructure {`);
  lines.push(`  clock: { now(): number };`);
  lines.push(`  logger: { log(message: string): void };`);
  lines.push(`}`);
  lines.push(``);

  for (let i = 1; i <= r.aggregates; i++) {
    appendAggregate(lines, i, r.commandsPerAggregate);
  }

  for (let p = 1; p <= r.projections; p++) {
    appendProjection(lines, p, r.aggregates);
  }

  for (let s = 1; s <= r.sagas; s++) {
    appendSaga(lines, s, r.aggregates);
  }

  lines.push(`export const aggregates = {`);
  for (let i = 1; i <= r.aggregates; i++) lines.push(`  Agg${i},`);
  lines.push(`} as const;`);
  lines.push(``);

  lines.push(`export const projections = {`);
  for (let p = 1; p <= r.projections; p++) lines.push(`  Proj${p},`);
  lines.push(`} as const;`);
  lines.push(``);

  if (r.sagas > 0) {
    lines.push(`export const sagas = {`);
    for (let s = 1; s <= r.sagas; s++) lines.push(`  Saga${s},`);
    lines.push(`} as const;`);
    lines.push(``);
  }

  lines.push(`export const domain = defineDomain({`);
  lines.push(`  writeModel: { aggregates },`);
  lines.push(`  readModel: { projections },`);
  if (r.sagas > 0) lines.push(`  processModel: { sagas },`);
  lines.push(`});`);
  lines.push(``);

  return lines.join("\n");
}

function appendAggregate(lines: string[], i: number, m: number): void {
  const Agg = `Agg${i}`;
  lines.push(`type ${Agg}State = { counter: number; lastValue: number };`);
  lines.push(`type ${Agg}Events = DefineEvents<{`);
  for (let k = 1; k <= m; k++) {
    lines.push(`  ${Agg}_Evt${k}: { id: string; value: number };`);
  }
  lines.push(`}>;`);
  lines.push(`type ${Agg}Commands = DefineCommands<{`);
  for (let k = 1; k <= m; k++) {
    lines.push(`  ${Agg}_Cmd${k}: { value: number };`);
  }
  lines.push(`}>;`);
  lines.push(`type ${Agg}Types = AggregateTypes & {`);
  lines.push(`  state: ${Agg}State;`);
  lines.push(`  events: ${Agg}Events;`);
  lines.push(`  commands: ${Agg}Commands;`);
  lines.push(`  infrastructure: StressInfra;`);
  lines.push(`};`);
  lines.push(`export const ${Agg} = defineAggregate<${Agg}Types>({`);
  lines.push(`  initialState: { counter: 0, lastValue: 0 },`);
  lines.push(`  decide: {`);
  for (let k = 1; k <= m; k++) {
    lines.push(`    ${Agg}_Cmd${k}: (command) => ({`);
    lines.push(`      name: "${Agg}_Evt${k}",`);
    lines.push(
      `      payload: { id: command.targetAggregateId, value: command.payload.value },`,
    );
    lines.push(`    }),`);
  }
  lines.push(`  },`);
  lines.push(`  evolve: {`);
  for (let k = 1; k <= m; k++) {
    lines.push(
      `    ${Agg}_Evt${k}: (payload, state) => ({ counter: state.counter + 1, lastValue: payload.value }),`,
    );
  }
  lines.push(`  },`);
  lines.push(`});`);
  lines.push(``);
}

function appendProjection(lines: string[], p: number, n: number): void {
  const Proj = `Proj${p}`;
  const a1 = ((p - 1) % n) + 1;
  const a2 = (p % n) + 1;
  lines.push(`type ${Proj}View = { count: number; lastValue: number };`);
  lines.push(`type ${Proj}Events =`);
  lines.push(`  | Extract<Agg${a1}Events, { name: "Agg${a1}_Evt1" }>`);
  lines.push(`  | Extract<Agg${a2}Events, { name: "Agg${a2}_Evt1" }>;`);
  lines.push(`type ${Proj}Queries = DefineQueries<{`);
  lines.push(
    `  ${Proj}_GetCount: { payload: { id: string }; result: ${Proj}View | null };`,
  );
  lines.push(`}>;`);
  lines.push(`type ${Proj}Types = ProjectionTypes & {`);
  lines.push(`  events: ${Proj}Events;`);
  lines.push(`  queries: ${Proj}Queries;`);
  lines.push(`  view: ${Proj}View;`);
  lines.push(`  infrastructure: StressInfra;`);
  lines.push(`};`);
  lines.push(`export const ${Proj} = defineProjection<${Proj}Types>({`);
  lines.push(`  initialView: { count: 0, lastValue: 0 },`);
  lines.push(`  on: {`);
  lines.push(`    Agg${a1}_Evt1: {`);
  lines.push(`      id: (event) => event.payload.id,`);
  lines.push(
    `      reduce: (event, view) => ({ count: view.count + 1, lastValue: event.payload.value }),`,
  );
  lines.push(`    },`);
  if (a1 !== a2) {
    lines.push(`    Agg${a2}_Evt1: {`);
    lines.push(`      id: (event) => event.payload.id,`);
    lines.push(
      `      reduce: (event, view) => ({ count: view.count + 1, lastValue: event.payload.value }),`,
    );
    lines.push(`    },`);
  }
  lines.push(`  },`);
  lines.push(`  queryHandlers: {`);
  lines.push(`    ${Proj}_GetCount: async (_query) => null,`);
  lines.push(`  },`);
  lines.push(`});`);
  lines.push(``);
}

function appendSaga(lines: string[], s: number, n: number): void {
  const Saga = `Saga${s}`;
  const a1 = ((s - 1) % n) + 1;
  const a2 = (s % n) + 1;
  const cmdAgg = (s % n) + 1;
  lines.push(`type ${Saga}State = { step: number };`);
  lines.push(`type ${Saga}Events =`);
  lines.push(`  | Extract<Agg${a1}Events, { name: "Agg${a1}_Evt1" }>`);
  if (a1 !== a2) {
    lines.push(`  | Extract<Agg${a2}Events, { name: "Agg${a2}_Evt1" }>;`);
  } else {
    lines[lines.length - 1] += `;`;
  }
  lines.push(
    `type ${Saga}Commands = Extract<Agg${cmdAgg}Commands, { name: "Agg${cmdAgg}_Cmd1" }>;`,
  );
  lines.push(`type ${Saga}Types = SagaTypes & {`);
  lines.push(`  state: ${Saga}State;`);
  lines.push(`  events: ${Saga}Events;`);
  lines.push(`  commands: ${Saga}Commands;`);
  lines.push(`  infrastructure: StressInfra;`);
  lines.push(`};`);
  lines.push(`export const ${Saga} = defineSaga<${Saga}Types>({`);
  lines.push(`  initialState: { step: 0 },`);
  lines.push(`  startedBy: ["Agg${a1}_Evt1"],`);
  lines.push(`  on: {`);
  lines.push(`    Agg${a1}_Evt1: {`);
  lines.push(`      id: (event) => event.payload.id,`);
  lines.push(`      handle: (event, state) => ({`);
  lines.push(`        state: { step: state.step + 1 },`);
  lines.push(`        commands: {`);
  lines.push(`          name: "Agg${cmdAgg}_Cmd1",`);
  lines.push(`          targetAggregateId: event.payload.id,`);
  lines.push(`          payload: { value: event.payload.value },`);
  lines.push(`        },`);
  lines.push(`      }),`);
  lines.push(`    },`);
  if (a1 !== a2) {
    lines.push(`    Agg${a2}_Evt1: {`);
    lines.push(`      id: (event) => event.payload.id,`);
    lines.push(
      `      handle: (_event, state) => ({ state: { step: state.step + 1 } }),`,
    );
    lines.push(`    },`);
  }
  lines.push(`  },`);
  lines.push(`});`);
  lines.push(``);
}
